name: StaffManager
main: com.github.SkyBirdSoar.Main.StaffManager
version: 1.0.4
Author: SkyBirdSoar
softdepend: [PermissionsEx, GroupManager]
depend: [Essentials]
commands:
   sm:
     description: Default StaffManager command.
     usage: /sm
     permission: sm.sm
     permission-message: You do not have permission to use this command.
   sma:
     description: StaffManager Administrative command.
     usage: /sma help
     permission: sma.help
     permission-message: You do not have permission to use this command.
permissions:
  sm.*:
    default: true
  sma.*:
    default: op
    children:
      sma.purge: false